# Generated by Django 4.1.7 on 2023-09-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='discount',
            new_name='shippingCost',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax',
        ),
    ]
