# Generated by Django 4.1.7 on 2023-09-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productsubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
