# Generated by Django 4.1.7 on 2023-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_discount_purchaseorder_shippingcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
