# Generated by Django 4.1.7 on 2023-10-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_purchaseorder_purchasedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitems',
            old_name='purchasePrice',
            new_name='price',
        ),
    ]
