# Generated by Django 4.1.7 on 2023-09-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_category_id_productsubcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='main.productsubcategory'),
        ),
    ]
