# Generated by Django 4.1.7 on 2023-09-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productcategory_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='subcategories',
        ),
    ]
