# Generated by Django 4.1.7 on 2023-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_purchaseprice_purchaseitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetransaction',
            name='refno',
            field=models.CharField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
