# Generated by Django 4.1.7 on 2023-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_purchasetransaction_refno'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetransaction',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
