# Generated by Django 4.1.7 on 2023-09-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productbrand_remove_productcategory_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcategory', to='main.productcategory'),
        ),
    ]
