# Generated by Django 4.1.7 on 2023-10-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_purchasetransaction_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='totalBalance',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='totalCost',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='totalPaid',
        ),
    ]
