# Generated by Django 4.1.7 on 2023-10-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_purchaseorder_totalbalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amountPaid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(max_length=64)),
                ('refno', models.CharField(max_length=256, unique=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('salesOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('salesDate', models.DateTimeField(blank=True, null=True)),
                ('refno', models.CharField(max_length=256, unique=True)),
                ('progressStatus', models.CharField(max_length=64)),
                ('paidStatus', models.CharField(max_length=64)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('discountPercent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxPercent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shippingCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.peoplecustomer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discountPercent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxPercent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productitem')),
                ('salesOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purchaseorder')),
            ],
        ),
    ]
