# Generated by Django 4.1.7 on 2023-09-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productsubcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='parent',
        ),
    ]
