# Generated by Django 4.1.7 on 2023-10-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_salesitems_salesorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='lastBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='lastCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='totalPaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
