# Generated by Django 4.1.7 on 2023-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_purchaseorder_lastbalance_purchaseorder_lastcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitems',
            name='sellingPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
