# Generated by Django 4.1.7 on 2023-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplesupplier',
            name='author',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='author',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
