# Generated by Django 4.1.7 on 2023-10-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_purchaseitems_sellingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='isRecentPurchased',
            field=models.BooleanField(default=False),
        ),
    ]
