# Generated by Django 4.1.7 on 2023-10-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productitem_isrecentpurchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='lastBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='lastCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='totalPaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
