# Generated by Django 4.1.7 on 2023-10-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_productitem_expirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='manufacturingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
